Feature/wom 116 - Add Subscription Form
nycrecords/womens_activism_nyc pull request #3
Opened 2018-07-24 13:50 UTC by eileen0810

This feature is an added subscribe option on the nav bar that allows one to subscribe using an email or phone number option and then added to the database. This feature also flashes a warning if only first name is given.

2018-07-24 19:20 UTC, zgary requested changes

2018-07-24 19:20 UTC, zgary commented on app/main/views.py
> +from flask import render_template, redirect, url_for, flash, request, Markup
Remove unused imports.

2018-07-24 19:20 UTC, gzhou1 commented on app/static/js/subscribe/subscribe.js
> +    });
This was probably added by accident. Remove this `});`

2018-07-24 19:20 UTC, gzhou1 commented on app/static/js/subscribe/subscribe.js
> +    $("#user-phone-field").keypress(function (key) {
Instead of using the jquery selector for the field, you can use the variable userPhone as you have initialized it in line 5.

2018-07-24 19:20 UTC, gzhou1 commented on app/static/js/subscribe/subscribe.js
> +    $("#user-first-name-field, #user-last-name-field").on('keyup', function () {
See comment above (you can use `userFirst` and `userLast`).

2018-07-24 19:20 UTC, gzhou1 commented on app/subscribe/forms.py
> +    StringField,
Remove unused imports.

2018-07-24 19:20 UTC, gzhou1 commented on app/subscribe/forms.py
> +    user_first = StringField("User first name", validators=[Optional(), Length(1, 128)])
Confirm with business owner if first or last name is required.

2018-07-24 19:20 UTC, gzhou1 commented on app/subscribe/utils.py
> +def create_user(user_first,
You can reuse the `create_user` method in `app/share/utils.py`. Maybe we should move the method into a more general utility file.

2018-07-24 19:20 UTC, gzhou1 commented on app/subscribe/views.py
> +from flask import render_template, redirect, url_for, flash, request, Markup
Remove unused import.

2018-07-24 19:20 UTC, gzhou1 commented on app/subscribe/views.py
> +
Add an additional new line for consistent formatting.

2018-07-24 19:20 UTC, gzhou1 commented on app/subscribe/views.py
> +
Remove an empty line.

2018-07-24 19:20 UTC, gzhou1 commented on app/subscribe/views.py
> +    return render_template('subscribe/subscribe.html', form=form)
Add new line at the end of the file.

2018-07-24 19:20 UTC, gzhou1 commented on app/templates/header.html
> +        <li id="nav-subscribe"><a href="{{ url_for('subscribe.subscribe')}}">Subscribe</a></li>
Add a space after `subscribe')`

2018-07-25 13:27 UTC, eileen0810 commented on app/subscribe/utils.py
> +def create_user(user_first,
Should I delete this file?

2018-07-25 13:29 UTC, eileen0810 commented on app/subscribe/forms.py
> +    user_first = StringField("User first name", validators=[Optional(), Length(1, 128)])
Should the validator for email and phone number change to DataRequired as well?

2018-07-25 19:24 UTC, zgary commented on app/subscribe/forms.py
> +    user_first = StringField("User first name", validators=[Optional(), Length(1, 128)])
As per business owner, first and last name are not required.

2018-07-25 19:30 UTC, zgary approved these changes

2018-07-25 19:30 UTC, merged